export const serviceWears = [
    { category: "cloth", name: "Agbada", amount: 2000 },
    { category: "cloth", name: "Blazer", amount: 700 },
    { category: "cloth", name: "Suit", amount: 700 },
    { category: "cloth", name: "Shirt", amount: 500 },
    { category: "cloth", name: "Joggers", amount: 300 },
    { category: "cloth", name: "Jeans", amount: 500 },
    { category: "cloth", name: "Leggings", amount: 300 },
    { category: "cloth", name: "Chinos", amount: 500 },
    { category: "cloth", name: "Kaftan", amount: 800 },
    { category: "cloth", name: "Sport Wears", amount: 300 },
    { category: "cloth", name: "Woman's Top/Trouser Wears", amount: 500 },
    { category: "cloth", name: "2 Piece of Khaki Uniform", amount: 1500 },
    { category: "cloth", name: "Skirt and Blouse", amount: 1000 },
    { category: "children wears", name: "Children 2pc Suit", amount: 600 },
    { category: "children wears", name: "Children School Uniform", amount: 350 },
    { category: "children wears", name: "Children Gown", amount: 350 },
    { category: "children wears", name: "Children Shirt", amount: 200 },
    { category: "children wears", name: "Children Trouser", amount: 150 },
    { category: "children wears", name: "Children Polo", amount: 150 },
    { category: "children wears", name: "Children Short", amount: 150 },
    { category: "outer wears", name: "Jeans Jacket", amount: 700 },
    { category: "outer wears", name: "Lap Coat", amount: 700 },
    { category: "outer wears", name: "Hoodie", amount: 800 },
    { category: "outer wears", name: "Winter/Leather Jacket", amount: 1000 },
    { category: "outer wears", name: "Tie", amount: 250 },
    { category: "house accessories", name: "Big Towel", amount: 1000 },
    { category: "house accessories", name: "Medium Towel", amount: 700 },
    { category: "house accessories", name: "Small Towel", amount: 500 },
    { category: "house accessories", name: "Outer Curtain", amount: 2000 },
    { category: "house accessories", name: "Inner Curtain", amount: 1000 },
    { category: "house accessories", name: "Round Curtain", amount: 2500 },
    { category: "house accessories", name: "Blanket", amount: 1000 },
    { category: "house accessories", name: "Duvet", amount: 2000 },
    { category: "house accessories", name: "Bedsheet", amount: 700 },
    { category: "house accessories", name: "Pillow Case", amount: 200 },
    { category: "house accessories", name: "Shoes", amount: 2000 },
    { category: "others", name: "Night Wears", amount: 800 },
    { category: "others", name: "Small Rug", amount: 4000 },
    { category: "others", name: "Medium Rug", amount: 7000 },
    { category: "others", name: "Large Rug", amount: 9000 },
    { category: "others", name: "Doormat", amount: 1500 },
    { category: "others", name: "Face Cap", amount: 250 },
    { category: "others", name: "Hat", amount: 300 },
]

export const serviceType =[
    {title: "Express", day: 1, id: 1},
    {title: "Regular", day: 5, id: 2},
]

export const locationState = [
    { name: "Abuja", id: 1 },
]

